class_path: lightning_diffusion.data.modules.HFDataModule
init_args:
  dataset_name: reach-vb/pokemon-blip-captions
  cache_dir: null
  batch_size: 32
  num_workers: 4
  dataset_cls: lightning_diffusion.data.t2i_datasets.HFStableDiffusionDataset
  dataset_args:
    image_column: image
    caption_column: text
    csv: metadata.csv