# lightning.pytorch==2.2.4
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}
      name: tb_logs
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  - class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ${trainer.default_root_dir}
      name: csv_logs
      version: null
      prefix: ''
      flush_logs_every_n_steps: 100
  #- class_path: lightning.pytorch.loggers.WandbLogger
  #  init_args:
  #    save_dir: ${trainer.default_root_dir}/
  #    project: ${trainer.default_root_dir}/
  callbacks:
  - class_path: lightning_diffusion.callback.VisualizeVideoCallback
    init_args:
      interval: 20
      height: 480
      width: 720
      by_epoch: false
      save_dir: ${trainer.default_root_dir}/videos
    dict_kwargs:
      prompt:
      - "BW_STYLE A black and white animated scene unfolds with an anthropomorphic goat surrounded by musical notes and symbols, suggesting a playful environment. Mickey Mouse appears, leaning forward in curiosity as the goat remains still. The goat then engages with Mickey, who bends down to converse or react. The dynamics shift as Mickey grabs the goat, potentially in surprise or playfulness, amidst a minimalistic background. The scene captures the evolving relationship between the two characters in a whimsical, animated setting, emphasizing their interactions and emotions"
      #- "BW_STYLE, masterpiece, bestquality, highlydetailed, ultradetailed, sunset"
      #- "BW_STYLE, orange sky, warm lighting, fishing boats, ocean waves seagulls"
      #- "BW_STYLE, rippling water, wharf, silhouette, serene atmosphere, dusk, evening glow"
      #- "BW_STYLE, golden hour, coastal landscape, seaside scenery"
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: null
      log_momentum: false
      log_weight_decay: false
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: ${trainer.default_root_dir}/ckpt
      filename: null
      monitor: train_loss
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: 1000
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: 3000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: null
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: lightning_logs/cogvideox
ckpt_path: null
model:
  class_path: CogVideoXModule
  init_args:
    base_model: THUDM/CogVideoX-5b
    gradient_checkpointing: true
    ucg_rate: 0.0
    enable_slicing: true
    enable_tiling: true
    enable_model_cpu_offload: true
    lora_rank: 128
    lora_alpha: 128

data:
  class_path: CogVideoXDataModule
  init_args:
    data_root: video-dataset-dir/
    dataset_file: dataset.csv
    caption_column: caption
    video_column: video_path
    max_num_frames: 49
    id_token: BW_STYLE
    height_buckets: [480]
    width_buckets: [720]
    frame_buckets: [49]
    load_tensors: false
    random_flip: null
    image_to_video: false
    video_reshape_mode: center
    batch_size: 1
    num_workers: 8
