# lightning.pytorch==2.2.4
seed_everything: true
trainer:
  accelerator: auto
  strategy: ddp_find_unused_parameters_true
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: tb_logs
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: null
      log_momentum: false
      log_weight_decay: false
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: lightning_logs/ckpt
      filename: null
      monitor: train_loss
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: 3000
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  - class_path: lightning_diffusion.callback.VisualizeVideoCallback
    init_args:
      save_dir: lightning_logs/videos
      interval: 100
      height: 512
      width: 512
      by_epoch: false
    dict_kwargs:
      clip_length: 24
      num_inference_steps: 20
      pose_vid:
        - 'data/pose.mp4'
        - 'data/pose.mp4'
        - 'data/pose.mp4'
        - 'data/pose.mp4'
        # 'https://raw.githubusercontent.com/MooreThreads/Moore-AnimateAnyone/master/configs/inference/pose_images/pose-1.png'
      ref_img:
        - 'https://raw.githubusercontent.com/MooreThreads/Moore-AnimateAnyone/master/configs/inference/ref_images/anyone-1.png'
        - 'https://raw.githubusercontent.com/MooreThreads/Moore-AnimateAnyone/master/configs/inference/ref_images/anyone-2.png'
        - 'https://raw.githubusercontent.com/MooreThreads/Moore-AnimateAnyone/master/configs/inference/ref_images/anyone-3.png'
        - 'https://raw.githubusercontent.com/MooreThreads/Moore-AnimateAnyone/master/configs/inference/ref_images/anyone-10.png'

  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: 30000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 0.01
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: lightning_logs
ckpt_path: null
model:
  class_path: AnimateAnyonePose2VidModule
  init_args:
    stage1_ckpt: 
    ucg_rate: 0.1
    noise_offset: 0.05
    snr_gamma: 5.0
    enable_zero_snr: true
data:
  class_path: AnimateAnyonePose2VidDataModule
  init_args:
    data_path: ../ubc_fashon_meta.jsonl
    batch_size: 1
    num_workers: 4
    dataset_args:
      sample_rate: 4
      n_sample_frames: 24
      width: 512
      height: 512
